-- =============================================================================
-- FILE PURPOSE:     MPI community database for the TW (Taiwan) region. Same structure
--                   as db_mpi_us.lua. Currently empty (no TW profiles in this snapshot).
-- LOAD ORDER:       Loads after db_mpi_kr.lua, before MidnightPI.lua.
-- DEFINES:          MidnightUI_MPI_DB["tw"] — realm→player score map for the TW region.
-- DO NOT EDIT:      Auto-generated by the MPI Companion App on each sync.
--                   Manual edits will be overwritten on next synchronization.
-- USED BY:          MidnightPI.lua — loaded and decoded when player is on a TW realm.
-- =============================================================================
-- MPI Community Database: TW Region
-- Generated: 2026-03-26T06:53:11.706Z
MidnightUI_MPI_DB = MidnightUI_MPI_DB or {}
MidnightUI_MPI_DB["tw"] = { realms = {}, data = "" }
