-- =============================================================================
-- FILE PURPOSE:     MPI community database for the KR (Korea) region. Same structure
--                   as db_mpi_us.lua. Currently empty (no KR profiles in this snapshot).
-- LOAD ORDER:       Loads after db_mpi_eu.lua, before db_mpi_tw.lua.
-- DEFINES:          MidnightUI_MPI_DB["kr"] — realm→player score map for the KR region.
-- DO NOT EDIT:      Auto-generated by the MPI Companion App on each sync.
--                   Manual edits will be overwritten on next synchronization.
-- USED BY:          MidnightPI.lua — loaded and decoded when player is on a KR realm.
-- =============================================================================
-- MPI Community Database: KR Region
-- Generated: 2026-03-26T06:53:11.705Z
MidnightUI_MPI_DB = MidnightUI_MPI_DB or {}
MidnightUI_MPI_DB["kr"] = { realms = {}, data = "" }
