-- =============================================================================
-- FILE PURPOSE:     MPI community database for the US region. Contains compressed
--                   per-player M+ performance scores indexed by realm and player name.
--                   The "data" field is a binary-packed string (delta-encoded, offset
--                   by realm). MidnightPI.lua decodes this at runtime to resolve scores
--                   for players found in C_LFGList search results.
-- LOAD ORDER:       Loads after db_mpi_metadata.lua, before db_mpi_eu.lua.
-- DEFINES:          MidnightUI_MPI_DB["us"] — realm→player score map for the US region.
-- DO NOT EDIT:      Auto-generated by the MPI Companion App on each sync.
--                   Manual edits will be overwritten on next synchronization.
-- USED BY:          MidnightPI.lua — db/mpi_sync.lua selects active region; MidnightPI
--                   then decodes MidnightUI_MPI_DB[region] for score lookups.
-- =============================================================================
-- MPI Community Database: US Region
-- Generated: 2026-03-26T06:53:11.704Z
-- Format version: 1
MidnightUI_MPI_DB = MidnightUI_MPI_DB or {}
MidnightUI_MPI_DB["us"] = {
  realms = {
    ["Proudmoore"] = { offset = 0, names = {"Jaina"} },
    ["Sargeras"] = { offset = 8, names = {"Thrall"} },
  },
  data = "\218\174\149\91\156\130\8\3\205\41\246\248\123\118\8\1",
}
