-- =============================================================================
-- FILE PURPOSE:     MPI community database for the EU region. Same structure as
--                   db_mpi_us.lua. Currently empty (no EU profiles in this snapshot).
-- LOAD ORDER:       Loads after db_mpi_us.lua, before db_mpi_kr.lua.
-- DEFINES:          MidnightUI_MPI_DB["eu"] — realm→player score map for the EU region.
-- DO NOT EDIT:      Auto-generated by the MPI Companion App on each sync.
--                   Manual edits will be overwritten on next synchronization.
-- USED BY:          MidnightPI.lua — loaded and decoded when player is on an EU realm.
-- =============================================================================
-- MPI Community Database: EU Region
-- Generated: 2026-03-26T06:53:11.705Z
MidnightUI_MPI_DB = MidnightUI_MPI_DB or {}
MidnightUI_MPI_DB["eu"] = { realms = {}, data = "" }
