-- =============================================================================
-- FILE PURPOSE:     MPI community database metadata. Stores aggregate stats for the
--                   full cross-region database: total profile count, per-region profile
--                   counts, realm counts, and observer counts. Used by MidnightPI.lua
--                   to display database size and by mpi_sync.lua for staleness checks.
-- LOAD ORDER:       Loads after mpi_sync.lua, before db_mpi_us.lua (second db/ file).
-- DEFINES:          MidnightUI_MPI_DBMeta (global table) — {version, generated, totalProfiles, regions{}}.
-- DO NOT EDIT:      Auto-generated by the MPI Companion App on each sync.
--                   Manual edits will be overwritten on next synchronization.
-- USED BY:          MidnightPI.lua — reads totalProfiles, regions for database status display.
-- =============================================================================
-- MPI Community Database Metadata
-- Generated: 2026-03-26T06:53:11.706Z
MidnightUI_MPI_DBMeta = {
  version = 1,
  generated = 1774507991,
  totalProfiles = 2,
  regions = {
    ["us"] = { profiles = 2, realms = 2, observers = 2 },
    ["eu"] = { profiles = 0, realms = 0, observers = 0 },
    ["kr"] = { profiles = 0, realms = 0, observers = 0 },
    ["tw"] = { profiles = 0, realms = 0, observers = 0 },
    ["cn"] = { profiles = 0, realms = 0, observers = 0 },
  },
}
