-- =============================================================================
-- FILE PURPOSE:     MPI sync checkpoint. Records the epoch timestamp of the last
--                   community database sync, the total profile count in the current
--                   snapshot, and the format version. Read by MidnightPI.lua on
--                   startup to determine whether a database refresh is needed.
-- LOAD ORDER:       Loads before MidnightPI.lua (first db/ file in TOC).
-- DEFINES:          MidnightUI_MPI_Sync (global table) — {lastSync, profileCount, version}.
-- DO NOT EDIT:      Auto-generated by the MPI Companion App on each sync.
--                   Manual edits will be overwritten on next synchronization.
-- USED BY:          MidnightPI.lua — reads lastSync to decide whether to prompt for refresh.
-- =============================================================================
-- Written by MPI Companion App
MidnightUI_MPI_Sync = {
  lastSync = 1774510482,
  profileCount = 2,
  version = 1,
}
